name: todo_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0-151.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6
  go_router: ^13.0.1
  flutter_localizations:
     sdk: flutter
  flutter_adaptive_scaffold: ^0.1.8
  uuid: ^4.3.3
  equatable: ^2.0.5
  either_dart: ^1.0.0
  mocktail: ^1.0.3
  flutter_bloc: ^8.1.4
  bloc_test: ^9.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:

   uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 